export default function Specifications() {
  return (
    <>
        <h2 className="headline">Product Specifications</h2>
        
       <table className="spec-table">
  <tr className="spec-table__first-row">
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>
  <tr>
    <td>xxxxxxxx</td>
    <td>xxxxxxx</td>
  </tr>

  
  
</table>
    </>
  );
}